import { useEffect, useState } from 'react';
import { useParams, Link } from 'react-router-dom';
import {
  CheckCircle2, MapPin, BedDouble, IndianRupee, Mail, Phone,
  FileSignature, ExternalLink, Sparkles, ShieldCheck,
} from 'lucide-react';
import toast from 'react-hot-toast';
import { api, apiMessage } from '../../services/api.js';
import { SECTIONS } from '../../config.js';
import TopBar from '../../components/shell/TopBar.jsx';
import LoadingScreen from '../../components/LoadingScreen.jsx';

// 7th-phase "Final preview" — read-only summary of everything that
// happened during onboarding: basics, ID, every captured section, the
// generated + signed contracts. Acts as the owner's permanent record of
// their listing once everything is live.

const fmtDate = (v) => (v ? new Date(v).toLocaleString() : '—');

const FinalPreviewPage = () => {
  const { id } = useParams();
  const [property, setProperty] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    let alive = true;
    api.get(`/owner/properties/by-id/${id}`)
      .then((r) => { if (alive) setProperty(r.data?.data?.property); })
      .catch((err) => toast.error(apiMessage(err, 'Could not load')))
      .finally(() => { if (alive) setLoading(false); });
    return () => { alive = false; };
  }, [id]);

  if (loading) return <div className="app-shell"><LoadingScreen /></div>;
  if (!property) return null;

  const contract = property.contract || {};
  const fields = property.fields || [];
  const isLive = property.status === 'completed';

  return (
    <div className="app-shell">
      <TopBar title="Final preview" />
      <main className="flex-1 overflow-y-auto p-4 pb-24 space-y-4">

        {/* Hero */}
        <section className={`rounded-2xl p-5 text-white shadow-card ${
          isLive
            ? 'bg-gradient-to-br from-violet-600 to-indigo-800'
            : 'bg-gradient-to-br from-slate-500 to-slate-700'
        }`}>
          <div className="flex items-start gap-3">
            <span className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-white/15">
              {isLive ? <Sparkles size={22} /> : <ShieldCheck size={22} />}
            </span>
            <div className="min-w-0">
              <p className="text-xs uppercase tracking-wider opacity-90">
                {isLive ? 'LISTING LIVE' : 'PREVIEW'}
              </p>
              <h2 className="mt-0.5 text-lg font-semibold leading-snug">{property.name}</h2>
              <p className="mt-0.5 text-xs opacity-90">{property.propertyCode}</p>
            </div>
          </div>
        </section>

        {/* Property facts */}
        <Section title="Property">
          <Row icon={MapPin} label="Address" value={property.address} />
          <Row icon={BedDouble} label="Rooms" value={property.numberOfRooms || '—'} />
          <Row icon={IndianRupee} label="Pricing" value={property.pricing || '—'} />
          <Row icon={Mail} label="Owner" value={`${property.ownerName} · ${property.ownerEmail}`} />
          {property.ownerPhone && <Row icon={Phone} label="Phone" value={property.ownerPhone} />}
        </Section>

        {/* Section snapshot */}
        <Section title={`Captured sections (${fields.length})`}>
          {fields.length === 0 ? (
            <p className="text-xs text-slate-500">No sections captured.</p>
          ) : (
            <ul className="space-y-1.5">
              {SECTIONS.map((s) => {
                const f = fields.find((x) => x.sectionKey === s.key);
                if (!f) return null;
                return (
                  <li key={s.key} className="flex items-center justify-between rounded-lg bg-slate-50 px-3 py-2 text-xs">
                    <span className="font-semibold text-slate-800">{s.label}</span>
                    <span className="text-slate-500">
                      {(f.photoUrls || []).length} photo{(f.photoUrls || []).length === 1 ? '' : 's'}
                    </span>
                  </li>
                );
              })}
            </ul>
          )}
        </Section>

        {/* Contract timeline */}
        <Section title="Contract">
          <Timeline
            items={[
              { label: 'Generated by reviewer', at: contract.generatedAt, done: !!contract.generatedAt },
              { label: 'Sent to you', at: contract.sentAt, done: !!contract.sentAt },
              { label: 'You uploaded signed copy', at: contract.signedAt, done: !!contract.signedAt },
              { label: 'Listing live', at: isLive ? property.updatedAt : null, done: isLive },
            ]}
          />

          {contract.generatedPdfUrl && (
            <a
              href={contract.generatedPdfUrl}
              target="_blank"
              rel="noreferrer"
              className="mt-3 inline-flex items-center gap-2 rounded-lg bg-slate-100 px-3 py-2 text-xs font-semibold text-slate-700 hover:bg-slate-200"
            >
              <FileSignature size={12} /> View original contract
              <ExternalLink size={11} />
            </a>
          )}
          {contract.signedPdfUrl && (
            <a
              href={contract.signedPdfUrl}
              target="_blank"
              rel="noreferrer"
              className="mt-2 ml-2 inline-flex items-center gap-2 rounded-lg bg-emerald-100 px-3 py-2 text-xs font-semibold text-emerald-800 hover:bg-emerald-200"
            >
              <CheckCircle2 size={12} /> View signed copy
              <ExternalLink size={11} />
            </a>
          )}
        </Section>

        {isLive && (
          <Link
            to="/owner"
            className="block rounded-2xl bg-violet-700 p-4 text-center text-sm font-semibold text-white hover:bg-violet-800"
          >
            Back to dashboard
          </Link>
        )}
      </main>
    </div>
  );
};

const Section = ({ title, children }) => (
  <section className="rounded-2xl border border-slate-100 bg-white p-4 shadow-card">
    <p className="text-[11px] font-semibold uppercase tracking-wider text-slate-500">{title}</p>
    <div className="mt-3 space-y-2">{children}</div>
  </section>
);

const Row = ({ icon: Icon, label, value }) => (
  <div className="flex items-start gap-2 text-sm">
    <Icon size={14} className="mt-0.5 shrink-0 text-slate-400" />
    <div className="min-w-0 flex-1">
      <p className="text-[10px] uppercase tracking-wider text-slate-500">{label}</p>
      <p className="truncate text-slate-800">{value}</p>
    </div>
  </div>
);

const Timeline = ({ items }) => (
  <ol className="relative space-y-3 pl-4">
    <span className="absolute left-1.5 top-1.5 bottom-1.5 w-px bg-slate-200" />
    {items.map((it, i) => (
      <li key={i} className="relative">
        <span className={`absolute -left-3 top-1.5 h-2.5 w-2.5 rounded-full ${
          it.done ? 'bg-emerald-600 ring-2 ring-emerald-100' : 'bg-slate-300 ring-2 ring-slate-100'
        }`} />
        <div className="ml-2">
          <p className={`text-xs font-semibold ${it.done ? 'text-slate-900' : 'text-slate-500'}`}>
            {it.label}
          </p>
          <p className="text-[10px] text-slate-400">{fmtDate(it.at)}</p>
        </div>
      </li>
    ))}
  </ol>
);

export default FinalPreviewPage;
