import { useEffect, useState } from 'react';
import { useParams, Link } from 'react-router-dom';
import {
  CheckCircle2, MapPin, BedDouble, Mail, Phone,
  FileSignature, ExternalLink, Sparkles, ShieldCheck,
} from 'lucide-react';
import toast from 'react-hot-toast';
import { api, apiMessage } from '../../services/api.js';
import TopBar from '../../components/shell/TopBar.jsx';
import LoadingScreen from '../../components/LoadingScreen.jsx';
import PropertyFullPreview from '../../components/PropertyFullPreview.jsx';

const fmtDate = (v) => (v ? new Date(v).toLocaleString() : '-');

const FinalPreviewPage = () => {
  const { id } = useParams();
  const [property, setProperty] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    let alive = true;
    api.get(`/owner/properties/by-id/${id}`)
      .then((r) => { if (alive) setProperty(r.data?.data?.property); })
      .catch((err) => toast.error(apiMessage(err, 'Could not load')))
      .finally(() => { if (alive) setLoading(false); });
    return () => { alive = false; };
  }, [id]);

  if (loading) return <div className="app-shell"><LoadingScreen /></div>;
  if (!property) return null;

  const contract = property.contract || {};
  const fields = property.fields || [];
  const isLive = property.status === 'completed';

  return (
    <div className="app-shell">
      <TopBar title="Final preview" />
      <main className="flex-1 overflow-y-auto p-4 pb-24 space-y-4">
        <section className={`rounded-2xl p-5 text-white shadow-card ${
          isLive
            ? 'bg-gradient-to-br from-violet-600 to-indigo-800'
            : 'bg-gradient-to-br from-slate-500 to-slate-700'
        }`}>
          <div className="flex items-start gap-3">
            <span className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-white/15">
              {isLive ? <Sparkles size={22} /> : <ShieldCheck size={22} />}
            </span>
            <div className="min-w-0">
              <p className="text-xs uppercase tracking-wider opacity-90">
                {isLive ? 'Listing live' : 'Preview'}
              </p>
              <h2 className="mt-0.5 text-lg font-semibold leading-snug">{property.name}</h2>
              <p className="mt-0.5 text-xs opacity-90">{property.propertyCode}</p>
            </div>
          </div>
        </section>

        <Section title="Property">
          <Row icon={MapPin} label="Address" value={property.address} />
          <Row icon={BedDouble} label="Rooms" value={property.numberOfRooms || '-'} />
          <Row icon={Mail} label="Owner" value={`${property.ownerName || '-'} - ${property.ownerEmail || '-'}`} />
          {property.ownerPhone && <Row icon={Phone} label="Phone" value={property.ownerPhone} />}
        </Section>

        <PropertyFullPreview fields={fields} />

        <Section title="Contract">
          <Timeline
            items={[
              { label: 'Generated by reviewer', at: contract.generatedAt, done: !!contract.generatedAt },
              { label: 'Sent to you', at: contract.sentAt, done: !!contract.sentAt },
              { label: 'You uploaded signed copy', at: contract.signedAt, done: !!contract.signedAt },
              { label: 'Officer uploaded final signed copy', at: contract.finalSignedAt, done: !!contract.finalSignedAt },
              { label: 'Listing live', at: isLive ? property.updatedAt : null, done: isLive },
            ]}
          />

          <div className="mt-3 space-y-1.5 text-xs">
            {contract.generatedPdfUrl && (
              <a href={contract.generatedPdfUrl} download target="_blank" rel="noreferrer" className="flex items-center gap-2 font-semibold text-slate-700">
                <FileSignature size={12} /> Download original contract <ExternalLink size={11} />
              </a>
            )}
            {contract.signedPdfUrl && (
              <a href={contract.signedPdfUrl} download target="_blank" rel="noreferrer" className="flex items-center gap-2 font-semibold text-emerald-700">
                <CheckCircle2 size={12} /> Download signed copy <ExternalLink size={11} />
              </a>
            )}
            {contract.finalPdfUrl && (
              <a href={contract.finalPdfUrl} download target="_blank" rel="noreferrer" className="flex items-center gap-2 font-semibold text-violet-700">
                <FileSignature size={12} /> Download final signed contract <ExternalLink size={11} />
              </a>
            )}
          </div>
        </Section>

        {isLive && (
          <p className="px-1 text-center text-xs text-slate-500">
            <Link to="/owner" className="font-semibold text-violet-700">Back to dashboard</Link>
          </p>
        )}
      </main>
    </div>
  );
};

const Section = ({ title, children }) => (
  <section className="rounded-2xl border border-slate-100 bg-white p-4 shadow-card">
    <p className="text-[11px] font-semibold uppercase tracking-wider text-slate-500">{title}</p>
    <div className="mt-3 space-y-2">{children}</div>
  </section>
);

const Row = ({ icon: Icon, label, value }) => (
  <div className="flex items-start gap-2 text-sm">
    <Icon size={14} className="mt-0.5 shrink-0 text-slate-400" />
    <div className="min-w-0 flex-1">
      <p className="text-[10px] uppercase tracking-wider text-slate-500">{label}</p>
      <p className="truncate text-slate-800">{value}</p>
    </div>
  </div>
);

const Timeline = ({ items }) => (
  <ol className="relative space-y-3 pl-4">
    <span className="absolute left-1.5 top-1.5 bottom-1.5 w-px bg-slate-200" />
    {items.map((it, i) => (
      <li key={i} className="relative">
        <span className={`absolute -left-3 top-1.5 h-2.5 w-2.5 rounded-full ${
          it.done ? 'bg-emerald-600 ring-2 ring-emerald-100' : 'bg-slate-300 ring-2 ring-slate-100'
        }`} />
        <div className="ml-2">
          <p className={`text-xs font-semibold ${it.done ? 'text-slate-900' : 'text-slate-500'}`}>
            {it.label}
          </p>
          <p className="text-[10px] text-slate-400">{fmtDate(it.at)}</p>
        </div>
      </li>
    ))}
  </ol>
);

export default FinalPreviewPage;
